# Generated by Django 5.1.2 on 2024-10-30 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='autor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentarios',
            name='data_comentario',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
