# Generated by Django 5.1.2 on 2024-10-30 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_comentarios_autor_comentarios_data_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='plataforma.noticia'),
        ),
    ]
